<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<persons>
    <treeSet>
        <name>a</name>
        <coordinates>
            <x>2</x>
            <y>2</y>
        </coordinates>
        <height>54</height>
        <eyeColor>GREEN</eyeColor>
        <hairColor>RED</hairColor>
        <nationality>CHINA</nationality>
        <location>
            <x>2.0</x>
            <y>2.0</y>
            <name>a</name>
        </location>
    </treeSet>
    <treeSet>
        <name>artem</name>
        <coordinates>
            <x>2</x>
            <y>25</y>
        </coordinates>
        <height>56</height>
        <eyeColor>BLUE</eyeColor>
        <hairColor>GREEN</hairColor>
        <nationality>USA</nationality>
        <location>
            <x>2.0</x>
            <y>3.0</y>
            <name>africa</name>
        </location>
    </treeSet>
</persons>
